// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information


//The messages the CLIENT should send to the server


//Almost all constants that don't end with _UPDATE shouldn't be expected to have anything on the mssage.
enum FNAFMESSAGE_FROM_CLIENT {
	VERSIONCHECK,
	SEND_CLIENT_STATE,
	SEND_CLIENT_OS,
	REQUEST_CLIENT_ID,
	REQUEST_FNAF_ATTACK,
	LOBBY_JOIN_REQUEST,
	LOBBY_STARTMATCH_REQUEST, // Uses Lobby Response
	LOBBY_LEAVE_REQUEST,
	SEND_CLIENT_USERNAME,
	SPECTATE_REQUEST,
	#region GAMEPLAY
	NIGHTEND_UPDATE = 239,
	LEFTDOOR_UPDATE = 240,
	RIGHTDOOR_UPDATE = 241,
	LEFTLIGHT_UPDATE = 242,
	RIGHTLIGHT_UPDATE = 243,
	CAMERAUP_UPDATE = 244,
	CAMERALOCK_UPDATE = 245,
	CURRENTCAMERA_UPDATE = 246,
	BONNIECAM_UPDATE = 247,
	CHICACAM_UPDATE = 248,
	FOXYCAM_UPDATE = 249,
	FREDDYCAM_UPDATE = 250,
	GOLDENFREDDYSTATE_UPDATE = 251,
	FREDDYPOWEROUTPHASE_UPDATE = 252,
	NIGHT_TIME_UPDATE = 253,
	POWERLEFT_UPDATE = 254,
	POWERUSAGE_UPDATE = 255
	#endregion
	
}

//The messages the SERVER should send to the client(s).
enum FNAFMESSAGE_FROM_SERVER
{
	KEEP_ALIVE,
	VERSIONCHECK,
	UPDATE_CLIENT_ID,
	SERVER_STATE_UPDATE,
	UPDATE_ALIVE_GUARDS,
	NEW_FNAF_ATTACK,
	#region LOBBY
	LOBBY_JOIN_RESPONSE,
	LOBBY_STATE_UPDATE,
	LOBBY_MASTER_UPDATE,
	LOBBY_STARTMATCH_RESPONSE,
	LOBBY_KICK_RESPONSE,
	LOBBY_SEND_USERNAMES_LIST,
	#endregion
	
	#region SPECTATING - should be same for client and server (240-255)
	SPECTATE_REQUEST_RESPONSE,
	SPECTATE_UPDATE_NIGHTEND = 239,
	SPECTATE_UPDATE_LEFTDOOR = 240,
	SPECTATE_UPDATE_RIGHTDOOR = 241,
	SPECTATE_UPDATE_LEFTLIGHT = 242,
	SPECTATE_UPDATE_RIGHTLIGHT = 243,
	SPECTATE_UPDATE_CAMERAUP = 244,
	SPECTATE_UPDATE_CAMERALOCK = 245,
	SPECTATE_UPDATE_CURRENTCAMERA = 246,
	SPECTATE_UPDATE_BONNIECAM = 247,
	SPECTATE_UPDATE_CHICACAM = 248,
	SPECTATE_UPDATE_FOXYCAM = 249,
	SPECTATE_UPDATE_FREDDYCAM = 250,
	SPECTATE_UPDATE_GOLDENFREDDYSTATE = 251,
	SPECATE_UPDATE_FREDDYPOWEROUTPHASE = 252,
	SPECTATE_UPDATE_CURRENTHOURS = 253,
	SPECTATE_UPDATE_POWERLEFT = 254,
	SPECTATE_UPDATE_POWERUSAGE = 255
	#endregion
}